config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'web/omniauth_callbacks' }
  scope '(:locale)', locale: /en|ru/ do
    devise_for :users, skip: :omniauth_callbacks, controllers: { sessions: 'web/devise/sessions',
                                                                 registrations: 'web/devise/registrations',
                                                                 passwords: 'web/devise/passwords',
                                                                 confirmations: 'web/devise/confirmations',
                                                                 unlocks: 'web/devise/unlocks' }
    namespace :api_internal do
      resources :users, only: [] do
        collection do
          get :search
        end
      end
    end

    scope module: :web do
      get '/403', to: 'errors#forbidden', as: :not_forbidden_errors
      get '/404', to: 'errors#not_found', as: :not_found_errors
      match '/500', to: 'errors#server_error', via: :all

      root 'home#index'
      resource :locale, only: [] do
        member do
          get :switch
        end
      end

      resource :employment, only: %i[show]

      resources :careers, only: %i[show] do
        scope module: :careers do
          resources :members, only: %i[show]
          resources :steps, only: [] do
            scope module: :steps do
              resources :members, only: [] do
                member do
                  patch :finish
                end
              end
            end
          end
        end
      end

      resources :vacancies, only: %i[index show]
      # NOTE: добавил валидацию на дирекшены что бы нельзя было указывать дерекшены типа node.js
      resources :vacancy_filters, only: %i[show] do
        collection do
          get :search
        end
      end
      resources :resumes do
        scope module: :resumes do
          resources :answers do
            member do
              patch :change_applying_state
            end
          end
          resources :pdfs, only: :show
          resources :comments
        end
      end
      resources :answers, only: [] do
        scope module: :answers do
          resources :comments
          resources :likes, only: %i[create destroy]
          resources :comments, only: %i[create update destroy]
        end
      end

      namespace :account do
        resources :resumes
        resources :vacancies
        resources :notifications, only: %i[index update]
        resource :newsletters, only: %i[edit update]
        resource :profile, only: %i[edit update show]
        scope module: :careers do
          resources :members, only: %i[index]
        end
      end

      resources :users
      resources :pages

      scope module: :hooks do
        resource :sparkpost
      end

      namespace :admin do
        root 'home#index'
        resources :users, only: %i[index edit update]
        resources :career_member_users, only: %i[index show new create] do
          collection do
            get :archived
            get :finished
            get :lost
          end
        end
        resources :resumes, only: %i[index edit update] do
          member do
            patch :archive
            patch :restore
          end
        end
        resources :vacancies, only: %i[index new create edit update]
        resources :careers, only: [] do
          scope module: :careers do
            collection do
              resources :steps, only: %i[index new show create edit update]
            end
          end
        end
        resources :careers, only: %i[index show new create edit update] do
          scope module: :careers do
            resources :items, only: %i[create]
            resources :members, only: %i[new create] do
              member do
                patch :archive
                patch :activate
              end
            end
          end
        end
      end
    end
  end
end

app/models/career.rb
# frozen_string_literal: true

class Career < ApplicationRecord
  extend Enumerize
  include CareerRepository

  validates :name, :description, :locale, presence: true
  validates :slug, presence: true, slug: true, uniqueness: { case_sensitive: false }
  has_many :items, class_name: 'Career::Item', dependent: :destroy
  has_many :steps, through: :items, source: :career_step
  has_many :members, class_name: 'Career::Member', dependent: :destroy
  has_many :users, through: :members

  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true
  enumerize :locale, in: I18n.available_locales

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at direction locale name slug]
  end
end

app/models/career/item.rb
# frozen_string_literal: true

class Career::Item < ApplicationRecord
  include Career::ItemRepository

  validates :career_step, uniqueness: { scope: :career }
  validates :order, uniqueness: { scope: :career }

  belongs_to :career_step, class_name: 'Career::Step', inverse_of: :career_items
  belongs_to :career
end

app/models/career/member.rb
# frozen_string_literal: true

class Career::Member < ApplicationRecord
  include StateConcern
  include Career::MemberRepository
  include Career::MemberPresenter

  validates :user, uniqueness: { conditions: -> { active } }

  belongs_to :user
  belongs_to :career
  has_many :career_step_members, class_name: 'Career::Step::Member', inverse_of: :career_member, foreign_key: 'career_member_id', dependent: :destroy

  aasm :state, timestamps: true do
    state :active, initial: true
    state :finished
    state :archived

    event :activate do
      transitions from: %i[archived], to: :active
    end

    event :finish do
      transitions from: %i[active], to: :finished, guard: :career_step_members_finished?
    end

    event :archive do
      transitions from: %i[active], to: :archived
    end
  end

  def can_show_step_body?(item)
    item.order <= current_item.order
  end

  def career_step_members_finished?
    career_step_members.ordered.finished.count == career.steps.ordered.count
  end

  def current_item
    career_items = career.items.ordered
    return career_items.last if finished?

    first_active_item = career_items.with_active_step_members(self).first

    return first_active_item if first_active_item

    last_finished_item = career_items.with_finished_step_members(self).last

    return next_item(last_finished_item) || career_items.first if last_finished_item

    career_items.first
  end

  def next_item(item)
    career.items.where(order: item.order..).ordered.second
  end

  def steps_count
    Rails.cache.fetch("member_step_count#{id}", expires_in: 12.hours) do
      career.steps.count
    end
  end

  def finished_steps_count
    Rails.cache.fetch("finished_step_count#{id}", expires_in: 1.hour) do
      career_step_members.where(career_step: career.steps).finished.count
    end
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at finished_at state updated_at user_id]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[user career]
  end
end

app/models/career/step.rb
# frozen_string_literal: true

class Career::Step < ApplicationRecord
  extend Enumerize
  include Career::StepRepository

  enumerize :locale, in: I18n.available_locales
  enumerize :notification_kind, in: %i[next_step_open_source], predicates: true

  validates :name, :description, :tasks_text, :locale, presence: true

  has_many :career_items, class_name: 'Career::Item', inverse_of: :career_step, foreign_key: 'career_step_id', dependent: :destroy
  has_many :careers, through: :career_items
  has_many :career_step_members, class_name: 'Career::Step::Member', inverse_of: :career_step, foreign_key: 'career_step_id', dependent: :destroy

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at direction locale name]
  end
end

app/models/career/step/member.rb
# frozen_string_literal: true

class Career::Step::Member < ApplicationRecord
  include StateConcern
  include Career::Step::MemberRepository

  validates :career_step, uniqueness: { scope: :career_member }

  belongs_to :career_step, class_name: 'Career::Step', inverse_of: :career_step_members
  belongs_to :career_member, class_name: 'Career::Member', inverse_of: :career_step_members
  has_one :user, through: :career_member

  aasm :state do
    state :active, initial: true
    state :finished

    event :finish do
      transitions from: :active, to: :finished
    end
  end
end

app/controllers/web/account/careers/application_controller.rb
# frozen_string_literal: true

class Web::Account::Careers::ApplicationController < Web::Account::ApplicationController
end

app/controllers/web/account/careers/members_controller.rb
# frozen_string_literal: true

class Web::Account::Careers::MembersController < Web::Account::Careers::ApplicationController
  def index
    scope = current_user.career_members.includes(:career)
    @active_members = scope.active
    @finished_members = scope.finished
  end
end

app/controllers/web/admin/careers/application_controller.rb
# frozen_string_literal: true

class Web::Admin::Careers::ApplicationController < Web::Admin::ApplicationController
  helper_method :resource_career

  def resource_career
    @resource_career ||= Career.find params[:career_id]
  end
end

app/controllers/web/admin/careers/members_controller.rb
# frozen_string_literal: true

class Web::Admin::Careers::MembersController < Web::Admin::Careers::ApplicationController
  def new
    @career_member = Career::Member.new
  end

  def create
    @career_member = Career::MemberMutator.create(resource_career, career_member_params)
    if @career_member.persisted?
      EmailSender.send_new_career_member_email(@career_member)
      f(:success)
      redirect_to admin_career_path(resource_career)
    else
      f(:error)
      render :new
    end
  end

  def archive
    member = Career::Member.find(params[:id])
    member.archive!
    f(:success)
    redirect_to params[:back_to] || admin_career_path(resource_career)
  end

  def activate
    member = Career::Member.find(params[:id])
    member.activate!
    f(:success)
    redirect_to params[:back_to] || admin_career_member_users_path
  end

  private

  def career_member_params
    params.require(:career_member).permit(:user_id)
  end
end

app/controllers/web/admin/careers/steps_controller.rb
# frozen_string_literal: true

class Web::Admin::Careers::StepsController < Web::Admin::Careers::ApplicationController
  def index
    query = { s: 'created_at desc' }.merge(params.permit![:q] || {})
    @q = Career::Step.ransack(query)
    @steps = @q.result.page(params[:page])
  end

  def show
    @step = Career::Step.find(params[:id])
    @careers = @step.careers
  end

  def new
    @step = Career::Step.new
  end

  def edit
    @step = Career::Step.find(params[:id])
    @careers = @step.careers
  end

  def create
    @step = Web::Admin::Career::StepForm.new(params[:career_step])
    if @step.save
      f(:success)
      redirect_to admin_step_path(@step)
    else
      f(:error)
      render :new, status: :unprocessable_entity
    end
  end

  def update
    step = Career::Step.find(params[:id])
    @step = step.becomes(Web::Admin::Career::StepForm)

    if @step.update(params[:career_step])
      f(:success)
      redirect_to admin_step_path(@step)
    else
      @careers = @step.careers
      f(:error)
      render :edit, status: :unprocessable_entity
    end
  end
end

app/controllers/web/admin/careers_controller.rb
# frozen_string_literal: true

class Web::Admin::CareersController < Web::Admin::ApplicationController
  def index
    query = { s: 'created_at desc' }.merge(params.permit![:q] || {})
    @q = Career.ransack(query)
    @careers = @q.result
  end

  def show
    @career = Career.find(params[:id])
    @career_steps = @career.steps.ordered.uniq
    @users = @career.users.distinct
  end

  def new
    @career = Career.new
  end

  def edit
    career = Career.find(params[:id])
    @career = career.becomes(Web::Admin::CareerForm)
    @items = @career.items
    @steps = Career::Step.all
  end

  def create
    @career = Web::Admin::CareerForm.new(params[:career])
    if @career.save
      f(:success)
      redirect_to admin_careers_path
    else
      f(:error)
      render :new, status: :unprocessable_entity
    end
  end

  def update
    career = Career.find(params[:id])
    @career = career.becomes(Web::Admin::CareerForm)
    if @career.update(params[:career])
      f(:success)
      redirect_to admin_careers_path
    else
      @steps = Career::Step.all
      f(:error)
      render :edit, status: :unprocessable_entity
    end
  end
end

app/controllers/web/careers/application_controller.rb
# frozen_string_literal: true

class Web::Careers::ApplicationController < Web::ApplicationController
  before_action :authenticate_user!
  helper_method :resource_career, :resource_member

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def resource_career
    @resource_career ||= Career.find_by!(slug: params[:career_id])
  end

  def resource_member
    @resource_member ||= Career::Member.find params[:id]
  end

  def user_not_authorized
    f(:error)
    redirect_to root_path
  end
end

app/controllers/web/careers/members_controller.rb
# frozen_string_literal: true

class Web::Careers::MembersController < Web::Careers::ApplicationController
  after_action :verify_authorized, only: %i[show]

  def show
    authorize resource_member
    @career_items = resource_career.items.ordered
    career_step_members = resource_member.career_step_members.ordered
    @career_step_members_by_step_id = career_step_members.index_by(&:career_step_id)
    @career_item = career_item
    @career_step = career_item.career_step
    @career_step_member = resource_member.career_step_members.find_or_create_by!(career_step: @career_step)
  end

  def career_item
    return resource_member.current_item unless params[:step]

    item_index = params[:step].to_i - 1

    if @career_items[item_index] && resource_member.can_show_step_body?(@career_items[item_index])
      @career_items[item_index]
    else
      @career_items.first
    end
  end
end

app/controllers/web/careers/steps/application_controller.rb
# frozen_string_literal: true

class Web::Careers::Steps::ApplicationController < Web::Careers::ApplicationController
end

app/controllers/web/careers/steps/members_controller.rb
# frozen_string_literal: true

class Web::Careers::Steps::MembersController < Web::Careers::Steps::ApplicationController
  after_action :verify_authorized, only: %i[finish]

  def finish
    career_step_member = Career::Step::Member.find(params[:id])
    authorize career_step_member
    career_member = career_step_member.career_member

    notification = Career::Step::MemberMutator.create!(career_step_member, career_member)

    EmailSender.send_notification_career(career_member, notification&.kind)
    f(:success)
    redirect_to career_member_path(resource_career.slug, career_member)
  end
end

app/controllers/web/careers_controller.rb
# frozen_string_literal: true

class Web::CareersController < Web::ApplicationController
  before_action :authenticate_user!

  def show
    @career = Career.find_by!(slug: params[:id])
    @career_member = Career::Member.find_by(user: current_user, career: @career)
  end
end

app/views/web/admin/careers/_form.html.slim
  .mb-3
    = f.input :name
  .mb-3
    = f.input :description, as: :markdown_editor
  .mb-3
    = f.input :slug
  .mb-3
    = f.input :locale

app/views/web/admin/careers/_item_step_fields.html.slim
.nested-fields.mb-3
  .row
    .col-md-7
      = f.association :career_step, collection: @steps, hint: t('.step')
    .col-md-2
      = f.input :order, hint: t('.order')
    .col-md-3
      - if f.object.career_step
        = link_to edit_admin_step_path(f.object.career_step), class: 'btn btn-outline-primary me-1', title: t('.edit') do
          span.bi.bi-gear-fill
      = link_to_remove_association f, class: 'btn btn-xs btn-danger', title: t('.remove_field') do
        span.bi.bi-trash3-fill

app/views/web/admin/careers/_menu.html.slim
ul.nav.nav-tabs.mb-4
  = menu_item t('.list'), admin_careers_path
  = menu_item t('.new'), new_admin_career_path
  - if career
    = menu_item t('.edit'), edit_admin_career_path(career)

app/views/web/admin/careers/_steps_list.html.slim
h3.mb-4.me-3 = t('.steps_career')

table.table
  thead
    tr
      th = han('career/step', 'name')
      th = han('career/step', 'created_at')
      th = t('actions')
  tbody
    - career_steps.each do |step|
      tr
        td = link_to step.name, admin_step_path(step), class: 'text-decoration-none'
        td = l step.created_at, format: :long
        td
          .btn-group[role='group' aria-label="#{t('action_buttons')}"]
            = link_to admin_step_path(step), class: 'btn btn-outline-primary btn-sm', title: t('.show_step') do
              span.bi.bi-eye-fill
            = link_to edit_admin_step_path(step), class: 'btn btn-outline-primary btn-sm', title: t('.edit') do
              span.bi.bi-gear-fill

app/views/web/admin/careers/_users.html.slim
h3.mb-4.me-3 = t('.users_career')

= link_to new_admin_career_member_path(@career), class: 'btn btn-primary mb-3' do
  span.bi.bi-lightning-charge.me-2
  = t('.add_user')
table.table
  thead
    tr
      th = han('user', 'name')
      th = han('user', 'email')
      th = han('career/member', 'created_at')
      th = han('career/member', 'finished_at')
      th = han('career/member', 'state')
      th = t('actions')
  tbody
    - users.each do |user|
      tr
        td = link_to user, user_path(user)
        td = user.email
        td = show_date_if(user.career_members.last.created_at, :long)
        td = show_date_if(user.career_members.last.finished_at, :long)
        td = user.career_members.last.aasm(:state).human_state
        td
          .btn-group[role='group' aria-label="#{t('action_buttons')}"]
            = link_to user_path(user), class: 'btn btn-outline-primary btn-sm' do
                span.bi.bi-eye-fill
            - if user.career_members.last.may_archive?
              = link_to archive_admin_career_member_path(career, user.career_members.last), method: :patch, data: { confirm: t('.question') }, class: 'btn btn-outline-danger btn-sm', title: t('.archive') do
                span.bi.bi.bi-trash3

app/views/web/admin/careers/edit.html.slim
- content_for :header do
  = @career.name

= render 'menu', career: @career

= simple_form_for @career, as: :career, url: admin_career_path(@career), wrapper: 'horizontal_form' do |f|
  p-0.pt-3.mb-5.hexlet-dashboard-courses
    ul.nav.nav-tabs.justify-content-center[role='tablist']
      li.nav-item
        a.nav-link.active[data-bs-toggle='tab' href='#career' role='tab'] = t('.career')
      li.nav-item
        a.nav-link[data-bs-toggle='tab' href='#items' role='tab'] = t('.items')
    .tab-content.pt-4
      .tab-pane.active[id='career' role='tabpanel']
        = render 'form', f:

      .tab-pane[id='items' role='tabpanel']
        .nested-fields.mb-3
          .row
            .col-md-1
            .col-md-7
              = t('.steps')
        = f.simple_fields_for :items, @career.items.ordered, wrapper: :inline_form do |item_form|
          = render 'item_step_fields', f: item_form
        .add_association.mt-3
          span.me-3
            = link_to_add_association f, :items, render_options: { wrapper: 'inline_form' }, partial: 'item_step_fields', class: 'btn btn-outline-primary' do
              = t('.add_step')
  .row.mt-5
    .col-sm.d-flex.mb-3
      .me-3 = f.button :submit, class: 'btn btn-success', name: 'create'
      = link_to t('.cancel'), url_for(:back), class: 'btn btn-outline-secondary'

app/views/web/admin/careers/index.html.slim
- content_for :header do
  = t('.career')

= render 'menu', career: nil

table.table
  thead
    tr
      th = sort_link(@q, 'name')
      th = sort_link(@q, 'slug')
      th = sort_link(@q, 'created_at')
      th = t('actions')
  tbody
    - @careers.each do |career|
      tr
        td = link_to career.name, admin_career_path(career), class: 'no decorete'
        td = career.slug
        td = l career.created_at, format: :long
        td
          .btn-group[role='group' aria-label="#{t('action_buttons')}"]
            = link_to admin_career_path(career), class: 'btn btn-outline-primary btn-sm' do
              span.bi.bi-eye-fill
            = link_to edit_admin_career_path(career), class: 'btn btn-outline-primary btn-sm', title: t('.edit') do
              span.bi.bi-gear-fill

app/views/web/admin/careers/new.html.slim
- content_for :header do
  = t('career')

= render 'menu', career: nil

= simple_form_for @career, as: :career, url: admin_careers_path, wrapper: 'horizontal_form' do |f|
  = render 'form', f:
  .row.mt-5
    .col-sm.d-flex.mb-3
      .me-3 = f.button :submit, class: 'btn btn-success', name: 'create'
      = link_to t('.cancel'), url_for(:back), class: 'btn btn-outline-secondary'

app/views/web/admin/careers/show.html.slim
- content_for :header do
  = t('.career_track', name: @career.name)

= link_to edit_admin_career_path(@career), class: 'btn btn-primary mb-3' do
  span.bi.bi-gear.me-2
  = t('.edit')

.row.mb-3
  .col-sm-3
    b = han('career', 'description')
  .col-sm-9.hexlet-cv-content
    == markdown2html @career.description

.row.mb-3
  .col-sm-3
    b = han('career', 'slug')
  .col-sm-9
    = @career.slug

.row.mb-5
  .col-sm-3
    b = han('career', 'locale')
  .col-sm-9
    = @career.locale_text

ul.nav.nav-tabs[role='tablist']
  li.nav-item
    a.nav-link.active[data-bs-toggle='tab' href='#users_career' role='tab'] = t('.users_career')
  li.nav-item
    a.nav-link[data-bs-toggle='tab' href='#steps' role='tab'] = t('.steps')

.tab-content.pt-4
  .tab-pane.active[id='users_career' role='tabpanel']
    = render 'users', users: @users, career: @career

  .tab-pane[id='steps' role='tabpanel']
    = render 'steps_list', career_steps: @career_steps, career: @career