config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'web/omniauth_callbacks' }
  scope '(:locale)', locale: /en|ru/ do
    devise_for :users, skip: :omniauth_callbacks, controllers: { sessions: 'web/devise/sessions',
                                                                 registrations: 'web/devise/registrations',
                                                                 passwords: 'web/devise/passwords',
                                                                 confirmations: 'web/devise/confirmations',
                                                                 unlocks: 'web/devise/unlocks' }
    namespace :api_internal do
      resources :users, only: [] do
        collection do
          get :search
        end
      end
    end

    scope module: :web do
      get '/403', to: 'errors#forbidden', as: :not_forbidden_errors
      get '/404', to: 'errors#not_found', as: :not_found_errors
      match '/500', to: 'errors#server_error', via: :all

      root 'home#index'
      resource :locale, only: [] do
        member do
          get :switch
        end
      end

      resource :employment, only: %i[show]

      resources :careers, only: %i[show] do
        scope module: :careers do
          resources :members, only: %i[show]
          resources :steps, only: [] do
            scope module: :steps do
              resources :members, only: [] do
                member do
                  patch :finish
                end
              end
            end
          end
        end
      end

      resources :vacancies, only: %i[index show]
      # NOTE: добавил валидацию на дирекшены что бы нельзя было указывать дерекшены типа node.js
      resources :vacancy_filters, only: %i[show] do
        collection do
          get :search
        end
      end
      resources :resumes do
        scope module: :resumes do
          resources :answers do
            member do
              patch :change_applying_state
            end
          end
          resources :pdfs, only: :show
          resources :comments
        end
      end
      resources :answers, only: [] do
        scope module: :answers do
          resources :comments
          resources :likes, only: %i[create destroy]
          resources :comments, only: %i[create update destroy]
        end
      end

      namespace :account do
        resources :resumes
        resources :vacancies
        resources :notifications, only: %i[index update]
        resource :newsletters, only: %i[edit update]
        resource :profile, only: %i[edit update show]
        scope module: :careers do
          resources :members, only: %i[index]
        end
      end

      resources :users
      resources :pages

      scope module: :hooks do
        resource :sparkpost
      end

      namespace :admin do
        root 'home#index'
        resources :users, only: %i[index edit update]
        resources :career_member_users, only: %i[index show new create] do
          collection do
            get :archived
            get :finished
            get :lost
          end
        end
        resources :resumes, only: %i[index edit update] do
          member do
            patch :archive
            patch :restore
          end
        end
        resources :vacancies, only: %i[index new create edit update]
        resources :careers, only: [] do
          scope module: :careers do
            collection do
              resources :steps, only: %i[index new show create edit update]
            end
          end
        end
        resources :careers, only: %i[index show new create edit update] do
          scope module: :careers do
            resources :items, only: %i[create]
            resources :members, only: %i[new create] do
              member do
                patch :archive
                patch :activate
              end
            end
          end
        end
      end
    end
  end
end

app/views/layouts/shared/_footer.html.slim
footer.bg-body-tertiary.border-top.py-4.mt-auto
  .container-xl
    .row.justify-content-lg-around
      .col-sm-6.col-md-4.col-lg-auto
        .mb-2
          = link_to t('.hexlet_html'), t('.hexlet_link'), class: 'text-body text-decoration-none fs-4', target: '_blank', rel: :noopener
        ul.list-unstyled
          li.mb-3 = link_to t('.rating'), users_path
          li.mb-3 = link_to t('.about'), page_path('about')
          li.mb-3 = link_to t('.source_code'), 'https://github.com/Hexlet/hexlet-cv', target: '_blank', rel: :noopener
          li = link_to 'Telegram #hexlet-volunteers', 'https://t.me/hexletcommunity/12', target: '_blank', rel: :noopener
      .col-sm-6.col-md-4.col-lg-auto
        .fs-4.mb-2 = t('.help')
        ul.list-unstyled
          li.mb-3 = link_to t('.success_stories'), 'https://ru.hexlet.io/blog/categories/success', target: '_blank', rel: :noopener
          li.mb-3 = link_to t('.test_assigments'), 'https://github.com/Hexlet/ru-test-assignments', target: '_blank', rel: :noopener
          li = link_to t('.employment_course'), 'https://ru.hexlet.io/courses/employment', target: '_blank', rel: :noopener
      .col-sm-6.col-md-4.col-lg-auto
        .fs-4.mb-2 = t('.additionally')
        ul.list-unstyled
          li.mb-3 = link_to t('.code_basics'), t('.basics_link'), target: '_blank', rel: :noopener
          li.mb-3 = link_to t('.code_battle'), 'https://codebattle.hexlet.io/', target: '_blank', rel: :noopener
          li.mb-3 = link_to t('.guides'), t('.guides_link'), target: '_blank', rel: :noopener
          li = link_to t('.recommended_books'), t('.books_link'), target: '_blank', rel: :noopener

= javascript_include_tag 'sentry', 'sprockets', 'application'

app/views/layouts/shared/_head.html.slim
= stylesheet_link_tag 'application', media: 'all'
= include_gon
meta charset="utf-8"
meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
= favicon_link_tag 'favicon.ico', sizes: 'any', rel: 'icon'
= favicon_link_tag 'icon.svg', type: 'image/svg+xml', rel: 'icon'
= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon'
= csp_meta_tag
= csrf_meta_tags
= auto_discovery_link_tag :rss, resumes_url(format: :rss)
= yield :meta
/ title = title
= display_meta_tags site: t('application_name'), reverse: true
/ = yield :js

- if Rails.env.production?
  = render 'layouts/deps/gtm_head'
  = render 'layouts/deps/ga'

app/views/layouts/shared/_last_answers.slim
.fs-4.mb-3 = t('.title')

- last_answers.each do |answer|
  .mb-4
    .fw-bolder = link_to answer.resume, resume_path(answer.resume, anchor: "answer-#{answer.id}")
    .small
      = truncate_markdown(answer.content, length: 90)
      .mt-1
        / span = t('.answers', count: answer.resume.answers.size)
        / | &nbsp;|&nbsp&nbsp
        = link_to answer.user, user_path(answer.user)

app/views/layouts/shared/_nav.html.slim
/ header.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-md-between.py-3.mb-4.border-bottom
nav.navbar.navbar-expand-lg.bg-body-tertiary
  .container
    a.navbar-brand(href=root_path)
      =image_tag "logo-cv-#{locale}.svg", class: 'align-baseline', width: 100
    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarSupportedContent
      ul.navbar-nav.me-auto
        = nav_menu_item t('.resumes'), root_path
        = nav_menu_item t('.vacancies'), vacancies_path
        = nav_menu_item t('.employment'), employment_path
      ul.navbar-nav
        - if user_signed_in?
          li.nav-item
            = link_to account_notifications_path, class: 'nav-link px-2' do
              - if current_user.unread_notifications.any?
                span.bi.bi-bell-fill.text-danger
              -else
                span.bi.bi-bell
          li.nav-item.dropdown
            a.nav-link.px-2.dropdown-toggle href="#" data-bs-toggle='dropdown' aria-haspopup='true' aria-expanded='false' = t('.add')
            ul.dropdown-menu.dropdown-menu-end
              li = link_to t('.add_resume'), new_account_resume_path, class: 'dropdown-item'
              li = link_to t('.add_vacancy'), new_account_vacancy_path, class: 'dropdown-item'
          li.nav-item.dropdown
            a.nav-link.px-2.dropdown-toggle href="#" data-bs-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
              span.bi.bi-person-circle
            ul.dropdown-menu.dropdown-menu-end
              li.dropdown-item-text.d-flex.align-items-center
                / .flex-shrink-0.me-2
                  / = image_tag 'user-avatar.png', width: 50, height: 50, alt: 'User Avatar', class: 'rounded-circle'
                .
                  .fw-bold = current_user
                  = current_user.email
              .dropdown-divider
              - if current_or_guest_user.admin?
                li = link_to t('.admin'), admin_root_path, class: 'dropdown-item'

              li = link_to t('.profile'), user_path(current_user), class: 'dropdown-item'
              li = link_to t('.my_resumes'), account_resumes_path, class: 'dropdown-item'
              li = link_to t('.my_vacancies'), account_vacancies_path, class: 'dropdown-item'
              li = link_to t('.settings'), edit_account_profile_path, class: 'dropdown-item'
              li = link_to t('.career'), account_members_path, class: 'dropdown-item'
              .dropdown-divider
              li = link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: 'dropdown-item'
          / = nav_menu_item t('.sign_out'), destroy_user_session_path, method: :delete
        - else
          = nav_menu_item t('.sign_in'), new_user_session_path
          = nav_menu_item t('.register'), new_user_registration_path
        li.nav-item.dropdown
          a.nav-link.dropdown-toggle href='#' data-bs-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
           span.me-2 = I18n.locale.upcase
          ul.dropdown-menu.dropdown-menu-end
            li
              - I18n.available_locales.without(I18n.locale).each do |locale|
                = link_to switch_locale_path(new_locale: locale), class: 'dropdown-item d-flex' do
                  = image_tag "flag-#{locale}.svg", width: 25, alt: "switch language to #{locale}", class: 'my-auto me-2'
                  span.my-auto = t(".#{locale}")