config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'web/omniauth_callbacks' }
  scope '(:locale)', locale: /en|ru/ do
    devise_for :users, skip: :omniauth_callbacks, controllers: { sessions: 'web/devise/sessions',
                                                                 registrations: 'web/devise/registrations',
                                                                 passwords: 'web/devise/passwords',
                                                                 confirmations: 'web/devise/confirmations',
                                                                 unlocks: 'web/devise/unlocks' }
    namespace :api_internal do
      resources :users, only: [] do
        collection do
          get :search
        end
      end
    end

    scope module: :web do
      get '/403', to: 'errors#forbidden', as: :not_forbidden_errors
      get '/404', to: 'errors#not_found', as: :not_found_errors
      match '/500', to: 'errors#server_error', via: :all

      root 'home#index'
      resource :locale, only: [] do
        member do
          get :switch
        end
      end

      resource :employment, only: %i[show]

      resources :careers, only: %i[show] do
        scope module: :careers do
          resources :members, only: %i[show]
          resources :steps, only: [] do
            scope module: :steps do
              resources :members, only: [] do
                member do
                  patch :finish
                end
              end
            end
          end
        end
      end

      resources :vacancies, only: %i[index show]
      # NOTE: добавил валидацию на дирекшены что бы нельзя было указывать дерекшены типа node.js
      resources :vacancy_filters, only: %i[show] do
        collection do
          get :search
        end
      end
      resources :resumes do
        scope module: :resumes do
          resources :answers do
            member do
              patch :change_applying_state
            end
          end
          resources :pdfs, only: :show
          resources :comments
        end
      end
      resources :answers, only: [] do
        scope module: :answers do
          resources :comments
          resources :likes, only: %i[create destroy]
          resources :comments, only: %i[create update destroy]
        end
      end

      namespace :account do
        resources :resumes
        resources :vacancies
        resources :notifications, only: %i[index update]
        resource :newsletters, only: %i[edit update]
        resource :profile, only: %i[edit update show]
        scope module: :careers do
          resources :members, only: %i[index]
        end
      end

      resources :users
      resources :pages

      scope module: :hooks do
        resource :sparkpost
      end

      namespace :admin do
        root 'home#index'
        resources :users, only: %i[index edit update]
        resources :career_member_users, only: %i[index show new create] do
          collection do
            get :archived
            get :finished
            get :lost
          end
        end
        resources :resumes, only: %i[index edit update] do
          member do
            patch :archive
            patch :restore
          end
        end
        resources :vacancies, only: %i[index new create edit update]
        resources :careers, only: [] do
          scope module: :careers do
            collection do
              resources :steps, only: %i[index new show create edit update]
            end
          end
        end
        resources :careers, only: %i[index show new create edit update] do
          scope module: :careers do
            resources :items, only: %i[create]
            resources :members, only: %i[new create] do
              member do
                patch :archive
                patch :activate
              end
            end
          end
        end
      end
    end
  end
end

app/models/vacancy.rb
# frozen_string_literal: true

class Vacancy < ApplicationRecord
  include StateConcern
  extend Enumerize
  extend TagVacancyPresenter
  include VacancyRepository
  include VacancyPresenter

  acts_as_taggable_on :technologies, :directions
  enumerize :employment_type, in: EMPLOYMENT_TYPES, default: 'full-time', predicates: true, scope: true
  enumerize :position_level, in: POSITION_LEVELS, default: 'junior', predicates: true, scope: true
  enumerize :salary_currency, in: %w[rub usd eur], default: 'rub'
  enumerize :salary_amount_type, in: %w[gross net depends], default: 'net'
  enumerize :location_of_position, in: %w[remote onsite hybrid], default: 'onsite'
  enumerize :locale, in: %i[en ru], default: :ru
  enumerize :kind, in: %i[hr habr], predicates: true, scope: true
  # Ex:- scope :active, -> {where(:active => true)}
  # enumerize :programming_language, in: PROGRAMMING_LANGAUGES, default: 'full-time', predicates: true, scope: true
  # enumerize :country_name, in: COUNTRIES, default: :user, predicates: true, scope: true

  validates :title, presence: true
  validates :kind, presence: true
  validates :contact_email, 'valid_email_2/email': true
  validates :company_name, presence: true
  validates :responsibilities_description, presence: true
  validates :site, presence: true, url: true
  validates :link_for_contact, url: { allow_blank: true }
  validates :position_level, presence: true
  validates :employment_type, presence: true
  validates :salary_from, presence: true,
                          numericality: { only_integer: true, greater_than: 0 },
                          unless: -> { salary_amount_type == :depends || salary_to&.positive? }
  validates :salary_to, presence: true,
                        numericality: { only_integer: true, greater_than: 0 },
                        unless: -> { salary_amount_type == :depends || salary_from&.positive? }
  validates :salary_currency, presence: true
  # validates :programming_language, presence: true

  belongs_to :creator, class_name: 'User'
  belongs_to :country, optional: true

  aasm :state, column: :state, timestamps: true do
    state :idle
    state :on_moderate
    state :published
    state :archived

    event :publish do
      transitions to: :published
    end

    event :send_to_moderate do
      transitions from: :idle, to: :on_moderate
    end

    event :archive do
      transitions to: :archived
    end
  end

  def initialize(attribute = nil)
    defaults = {
      locale: I18n.locale,
      kind: :hr
    }

    attrs_with_defaults = attribute ? defaults.merge(attribute) : defaults
    super(attrs_with_defaults)
  end

  def salary?
    salary_from? || salary_to?
  end

  def to_s
    title
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[id kind title state name company_name created_at published_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[technologies creator]
  end

  def need_escape_html?
    !habr?
  end
end

app/controllers/web/account/vacancies_controller.rb
# frozen_string_literal: true

class Web::Account::VacanciesController < Web::Account::ApplicationController
  after_action :verify_authorized, only: %i[edit update]

  def index
    @vacancies = current_user.vacancies.with_locale
  end

  def new
    @vacancy = Web::Account::VacancyForm.new
  end

  def edit
    vacancy = current_user.vacancies.find params[:id]
    @vacancy = vacancy.becomes(Web::Account::VacancyForm)
    authorize vacancy
  end

  def create
    @vacancy = Web::Account::VacancyForm.new(params[:vacancy])
    @vacancy.creator = current_user

    if @vacancy.save
      f(:success)
      redirect_to account_vacancies_path
    else
      f(:error)
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @vacancy = current_user.vacancies.find params[:id]
    authorize @vacancy
    vacancy = @vacancy.becomes(Web::Account::VacancyForm)
    if vacancy.update(params[:vacancy])
      change_visibility(@vacancy)
      f(:success)
      redirect_to account_vacancies_path
    else
      @vacancy = vacancy.becomes(Vacancy)
      f(:error)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy; end

  private

  def change_visibility(vacancy)
    vacancy.archive! if params[:archive]
  end
end

app/controllers/web/admin/vacancies_controller.rb
# frozen_string_literal: true

class Web::Admin::VacanciesController < Web::Admin::ApplicationController
  def index
    query = { s: 'created_at desc' }.merge(params.permit![:q] || {})
    respond_to do |format|
      format.html do
        @q = Vacancy.ransack(query)
        @vacancies = @q.result(distinct: true).page(params[:page])
      end

      format.csv do
        q = Vacancy.includes(:creator).ransack(query)
        vacancies = q.result(distinct: true)

        headers = %w[id title state creator company_name created_at published_at]
        send_file_headers!(filename: "vacancies-#{Time.zone.today}.csv")
        self.response_body = generate_csv(vacancies, headers) do |vacancy|
          [
            vacancy.id,
            vacancy.title,
            vacancy.aasm(:state).human_state,
            "#{vacancy.creator.email}(#{vacancy.creator.first_name} #{vacancy.creator.last_name})",
            vacancy.company_name,
            l(vacancy.created_at, format: :long),
            show_date_if(vacancy.published_at, :long)
          ]
        end
      end
    end
  end

  def new
    @vacancy = Web::Admin::VacancyForm.new
  end

  def edit
    vacancy = Vacancy.find params[:id]
    @vacancy = vacancy.becomes(Web::Admin::VacancyForm)
  end

  def create
    @vacancy = Web::Account::VacancyForm.new(params[:vacancy])
    @vacancy.creator = current_user

    if @vacancy.save
      f(:success)
      redirect_to admin_vacancies_path
    else
      f(:error)
      render :new, status: :unprocessable_entity
    end
  end

  def update
    vacancy = Vacancy.find params[:id]
    @vacancy = vacancy.becomes(Web::Admin::VacancyForm)
    if @vacancy.update(params[:vacancy])
      f(:success)
      redirect_to edit_admin_vacancy_path(@vacancy)
    else
      render :edit, status: :unprocessable_entity
    end
  end
end

app/controllers/web/vacancies_controller.rb
# frozen_string_literal: true

class Web::VacanciesController < Web::ApplicationController
  def index
    q = Vacancy.web.includes(:technologies).ransack(params[:q])
    @vacancies = q.result(distinct: true).page(params[:page]).order(published_at: :desc)
    @vacancy_search_form = Web::Vacancies::SearchForm.new
    @tags = Vacancy.directions_tags
    @page = params[:page]

    respond_to do |format|
      format.html
      format.rss
    end
  end

  def show
    @vacancy = Vacancy.find(params[:id])
    respond_with @vacancy, location: resume_url(@vacancy)
  end
end

app/views/web/admin/vacancies/_form.html.slim
= simple_form_for vacancy, as: :vacancy, url:, wrapper: 'horizontal_form' do |f|
  .mb-3
    = f.input :state_event, as: :state_event
  .mb-3
    = f.input :locale
  .mb-3
    = f.submit class: 'btn btn-outline-primary'
  .mb-3
    = f.input :position_level
  .mb-3
    = f.input :salary_amount_type
  .mb-3
    = f.input :location_of_position
  .mb-3
    = f.input :employment_type
  .mb-3
    = f.input :salary_from
  .mb-3
    = f.input :salary_to
  .mb-3
    = f.input :salary_currency
  .mb-3
    = f.input :title
  .mb-3
    = f.input :city_name
  .mb-3
    = f.input :location
  .mb-3
    = f.input :company_name
  .mb-3
    = f.input :site
  .mb-3
    = f.input :contact_name
  .mb-3
    = f.input :contact_phone
  .mb-3
    = f.input :contact_telegram
  .mb-3
    = f.input :contact_email
  .mb-3
    = f.input :link_for_contact
  .mb-3
    = f.input :experience_description, as: :text, input_html: { rows: 10 }
  .mb-3
    = f.input :about_company, as: :text, input_html: { rows: 10 }
  .mb-3
    = f.input :about_project, as: :text, input_html: { rows: 10 }
  .mb-3
    = f.input :responsibilities_description, as: :text, input_html: { rows: 20 }
  .mb-3
    = f.input :requirements_description, as: :text, input_html: { rows: 20 }
  .mb-3
    = f.input :conditions_description, as: :text, input_html: { rows: 20 }
  .mb-3
    = f.input :technology_list, input_html: { value: f.object.technology_list.to_s }
  .mb-3
    = f.input :direction_list, input_html: { value: f.object.direction_list.to_s }
  .row.mt-5
    .col-sm.d-flex.mb-3
      .me-3 = f.button :submit, class: 'btn-primary'
    .col-sm.d-flex.justify-content-end.mb-3
      = link_to t('.cancel'), url_for(:back), class: 'btn btn-outline-secondary'

app/views/web/admin/vacancies/_menu.html.slim
ul.nav.nav-tabs.mb-4
  = menu_item t('.list'), admin_vacancies_path
  = menu_item t('.new'), new_admin_vacancy_path
  - if @vacancy&.persisted?
    = menu_item @vacancy.title, edit_admin_vacancy_path(@vacancy)

app/views/web/admin/vacancies/_search_form.html.slim
.p-3.mb-3.bg-light
  = search_form_for q, default_filter_form_options(url: admin_vacancies_path, html: { class: 'row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-xl-4 g-2 g-lg-3', novalidate: true }) do |f|
    = f.input :company_name_cont, placeholder: han('vacancy', :company_name), label: false
    = f.input :creator_first_name_or_creator_last_name_or_creator_email_cont, label: false, placeholder: t('.creator')
    = f.input :state_eq, collection: states_for_select(Vacancy), prompt: han('vacancy', :state), include_blank: true, label: false
    = f.input :kind_eq, collection: Vacancy.kind.options, prompt: han('vacancy', :kind), include_blank: true, label: false
    = f.input :created_at_gteq, as: :date, html5: true, label: t('.created_at_from')
    = f.input :created_at_lteq, as: :date, html5: true, label: t('.created_at_to')
    .col.d-flex.align-self-end
      = f.button :submit, t('submit'), class: 'btn-primary me-2 flex-grow-1'
      = link_to t('reset'), url_for, class: 'btn btn-outline-primary'

app/views/web/admin/vacancies/edit.html.slim
- content_for :header do
  = t('.header')

= render 'menu'

= render 'form', vacancy: @vacancy, url: admin_vacancy_path

app/views/web/admin/vacancies/index.html.slim
= link_to url_for(params.permit!.merge(format: 'csv')) do
    span.bi.bi-file-earmark-spreadsheet
      = t('.export')

= render 'search_form', q: @q

= render 'menu'

table.table
  thead
    tr
      th = sort_link(@q, 'id')
      th = sort_link(@q, 'title')
      th = sort_link(@q, 'state')
      th = sort_link(@q, 'creator')
      th = sort_link(@q, 'company_name')
      th = sort_link(@q, 'created_at')
      th = sort_link(@q, 'published_at')
      td = t('actions')
  tbody
    - @vacancies.each do |vacancy|
      tr
        td = link_to vacancy.id, edit_admin_vacancy_path(vacancy)
        td = link_to vacancy, vacancy_path(vacancy)
        td = vacancy.aasm(:state).human_state
        td = link_to vacancy.creator, user_path(vacancy.creator)
        td = vacancy.company_name
        / td = user.role
        td = l vacancy.created_at, format: :long
        td = show_date_if(vacancy.published_at, :long)
        td
          .btn-group[role='group' aria-label="#{t('action_buttons')}"]
            = link_to vacancy_path(vacancy), class: 'btn btn-outline-primary btn-sm' do
              span.bi.bi-eye-fill
            = link_to edit_admin_vacancy_path(vacancy), class: 'btn btn-outline-primary btn-sm', title: t('.edit') do
              span.bi.bi-gear-fill

= paginate @vacancies

app/views/web/admin/vacancies/new.html.slim
- content_for :header do
  = t('.new_vacancy')

= render 'menu'

= render 'form', vacancy: @vacancy, url: admin_vacancies_path